### PR TITLE
Adjusting docs and man pages, as well as updating links.

### PR DESCRIPTION
**Pull request by rbisewski**
While using efibootmgr the other day, I noticed a few of the links were a tad stale in several documentation files, and that the man page had detached numbers in the *Examples* section as well as an old version number.

I suspect at one time this was generated and then left alongside over the years. So I took a few minutes to correct these minor issues and clean up a bit; let me know what you think.

### CODE REVIEW

**Comment by rbisewski** [comment]
Any update on this? Or has this repo moved on?

**Comment by vathpela** [comment]
Your commit message says it "adjusts" things, but it makes no mention of why.  Updating the URLs makes sense, but what's the rationale for reformatting INSTALL (for example)?

**Comment by vathpela** [comment]
I've pushed this with some minor changes.  If you think there's anything important I've missed, please do feel free to re-open this.

**Comment by rbisewski** [comment]
Glad you followed up :+1: 

The goal of this branch is to fix both the URLs in the number of places and to correct what appear to be issues with the `man` page, as noted in this [screenshot](https://imgur.com/a/gA5Cz).

Specifically, the `INSTALL` file itself also had URLs that needed to be corrected. Finally, thanks again for merging this in and making the necessary minor changes :)

**Pull request closed without merging**
