### PR TITLE
Implementation of #108 (ability to set LOAD_OPTION_FORCE RECONNECT)

### PR DESCRIPTION
**Pull request by slytomcat**
It is possible implementation of #108

### CODE REVIEW

**Comment by slytomcat** [comment]
Sorry for my mistakes. All fixed now.

**Comment by vathpela** [comment]
Thanks!  I've pushed this to master - though I squashed it all as one patch and did some minor cleanups.  Check and make sure it's all okay, and re-open this if it isn't.

**Comment by Vlad1mir-D** [comment]
Unbelievable level of narcissism.
I imagine you clapped yourself with a smile, winked and then yelled something like "WOW! I'M SO COOL!" when you [wrote](https://habr.com/ru/post/471266/) about how you wrote this ~~PR~~Utter Crap.
Please never ever again make contributions to open-source projects.

**Comment by AndreiShostik** [comment]
@Vlad1mir-D chill out, man
does it look good?
does it work fine? 
so what's the problem? why is your 5th point on fire?

**Comment by slytomcat** [comment]
@Vlad1mir-D, don't learn me how to live and I wouldn't tell where you have to go.

I've wrote that article just for fan, being glad that this PR is finally accepted. If you don't share my joyfulness for it - it is only your problem.

**Comment by Vlad1mir-D** [comment]
Yep, it's pretty typical for the modern kind of such called "developers" to achieve joyfulness through the attention-whoring instead of joyfulness through the process of creating strong technical solutions.
Go on and code some additional Code of Conduct and then share your joyfulness of such a fascinating fact.

**Comment by slytomcat** [comment]
@Vlad1mir-D, yep it's typical for old people such called himself "developers" to get the satisfaction by instructing everybody around what to do and how to do.

Go ahead, but teach your children (if you have). I don't need your lessons.

**Comment by slytomcat** [comment]
... about "strong technical solutions" - have you found some technical defect in this PR? If yes, I'm ready to discuss it. All the rest is off-topic hire and I insist that you have to stop this useless words flow.

**Comment by asavah** [comment]
Was this (crap) even runtime tested?
This breaks normal efibootmgr behavior https://github.com/rhboot/efibootmgr/issues/119

**Comment by Vlad1mir-D** [comment]
>insist that you have to stop this useless words flow

Go insist somewhere else.

**Comment by slytomcat** [comment]
@Vlad1mir-D, you know where exactly you have to go.

**Pull request closed without merging**
